spring.application.name=plazavea-api

spring.datasource.url=jdbc:oracle:thin:@//192.168.18.111:1521/XEPDB1
spring.datasource.username=here_maps
spring.datasource.password=Sistemas25
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.address=0.0.0.0
server.port=8080

app.security.password-reset.otp-expiration-minutes=3
app.security.password-reset.max-attempts=3
app.security.password-reset.max-resends=3
app.security.password-reset.generic-message=Si los datos ingresados son correctos, recibirás un código de verificación por correo electrónico.

app.integration.email.enabled=true
app.integration.email.from=joaquinku02@gmail.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=joaquinkut02@gmail.com
spring.mail.password=trys mzqc btzp kdfj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

